import { SUPER_GLUE_NAME } from "./products";

/**
 * Production language: English only.
 * Audience: general consumer.
 * Tone: professional, clear, and welcoming — not slang, not stiff.
 *
 * Product names are interpolated rather than hardcoded so that retargeting the
 * advisor at a different adhesive does not require touching this file.
 */
export const copy = {
  brand: "Fix Finder",
  catalog: "Buy Solution",
  headline: "Something's broke?\nDon't worry, we got you!",
  camera: "Take a photo",
  gallery: "Browse Gallery",
  dropHint: "Drag a photo here, or choose an option below",
  dropSubHint: "JPG or PNG works best",
  remove: "Remove",
  notePlaceholder: "Describe the item (optional)",
  submit: "Let's fix it!",
  analyzing: "Analyzing photo…",
  analyzingAnswer: "Checking your answer…",
  clarifyingLead: "One quick question so we can recommend the right fix.",
  orTypeAnswer: "or type your own answer",
  customAnswerPlaceholder: "Your answer",
  sendAnswer: "Continue",
  addClarifyingAnswer: "Please choose an option or type a short answer.",
  addPhoto: "Please add a photo.",
  usePhoto: "Please use a photo file.",
  tryAgain: "Something went wrong. Please try again.",
  recommended: "Recommended amount",
  recommendedAmountIs: `Recommended amount of ${SUPER_GLUE_NAME} is`,
  recommendedProduct: SUPER_GLUE_NAME,
  packClaims: "Instant strength · water and dishwasher resistant",
  packNeedOne: "You'll need 1 pack",
  packNeedMany: "You'll need {n} packs",
  packSize: "3 g per pack",
  needHelp: "We're here to help",
  notAFit: "Super glue isn't the right fit",
  supportLead:
    "That's okay — super glue isn't the right fit here. Keep the pieces, and we'll help you find the right adhesive.",
  nextSteps: "What to do next:",
  supportEncouragement:
    "Don't worry, we've got you. An adhesive specialist will help you find the right product.",
  buyProduct: `Buy ${SUPER_GLUE_NAME}`,
  buyShopee: "Shopee",
  buyLazada: "Lazada",
  buyStoreLocator: "Find a store",
  contactSupport: "Contact support",
  howTo: "How to fix it:",
  encouragement:
    "You've got this. People have been making lasting repairs with a good adhesive for generations — this one can hold too.",
  aiNote:
    "This recommendation is AI-generated from your photo. It's a guide, not a guarantee — always follow the instructions on the pack.",
  aiNoteAsk: "Ask a specialist",
  sample: "Sample recommendation",
  object: "Object",
  material: "Material",
  damage: "Damage",
  seeResults: "See real results",
  realResults: "Successful fixes from the community!",
  realResultsLead: "Made possible by",
  seeMore: "Browse more",
  learnMore: "Do you want to learn more DIY fixes?",
  goToHub: "Go to the Learning Hub",
  hubTitle: "Learning Hub",
  hubLead:
    "Short lessons for everyday repairs — then fix it, and share what you saved.",
  hubBack: "Home",
  backToHub: "Back to Learning Hub",
  startLesson: "Start this lesson",
  examplesHeading: "You'll see this on",
  yourNextStep: "Your recommended next step",
  pickToContinue: "Choose an option to see the tutorial.",
  tryAnotherItem: "Try another item",
  rightCall: "That's the right call.",
  betterCall: "Here's a better way to look at it.",
  canGlueFix: `Can ${SUPER_GLUE_NAME} fix this?`,
  nextLesson: "Next lesson",
  openFixFinder: "Open Fix Finder",
  campaignLoop:
    "Learn it here, fix it for real, then share the before and after — that's how the next person decides to try.",
  whatYouLearn: "What you'll learn",
  lessonHook: "30-second lesson",
  tryThis: "Try this",
  learnFixShare: "Learn → Fix → Share",
  learnStep: "Learn",
  learnStepNote: "A 30–60 second professional tutorial.",
  fixStep: "Fix",
  fixStepNote: "Step-by-step repair guide, plus the recommended product.",
  shareStep: "Share",
  shareStepNote: "Upload your before and after.",
  shareHashtag: "#FixBeforeYouToss",
  scanToFix: "Scan to try Fix Finder",
  shareInviteHub: "Share your repair. It helps someone else try theirs.",
  shareInvite: "Your item got fixed? Let the community know. Share your story.",
  writePost: "Write a post",
  communityTitle: "Community fixes",
  communityLead: "Before-and-after stories from people who used Fix Finder.",
  postTitle: "What did you fix?",
  postAuthor: "Your name or username (optional)",
  postAuthorHint: "Leave this blank to stay anonymous.",
  postedBy: "by",
  anonymous: "Anonymous",
  postProduct: "Product used (optional)",
  postNote: "Share your thoughts",
  postBefore: "Before photo",
  postAfter: "After photo",
  editField: "Edit",
  fromScanHint:
    "We filled this from your latest Fix Finder scan. Tap the pencil if you want to change anything.",
  publishPost: "Share with the community",
  postGuidelines:
    "Posts are reviewed automatically. Share a real before-and-after of the same repair — no spam, ads, or harmful photos.",
  postRejected: "This post could not be published. Please share a genuine repair story.",
  reviewingPost: "Reviewing your story…",
  backHome: "Back to Fix Finder",
  backCommunity: "Back to Community fixes",
  tryAnother: "Fix another item",
  copySteps: "Copy",
  downloadSteps: "Download",
  printSteps: "Print",
  copied: "Copied",
  saved: "Saved",
  printed: "PDF saved",
  uploadedPhoto: "Your photo",
  before: "Before",
  after: "After",
  beforeAfterSlider: "Drag to compare before and after",
  cameraDenied: "Please allow camera access, or use Browse Gallery.",
  capturePhoto: "Capture",
  closeCamera: "Close",
  postedBanner: "Your story is live. Thank you for sharing.",
  postedThanksKicker: "Your story is live",
  postedThanksTitle: "Thank you for sharing!",
  postedThanksLead:
    "A real before-and-after helps someone else try a repair instead of throwing the item away.",
  seeInCommunity: "See it in Community fixes",
  shareYourFix: "Share your fix",
  shareYourFixLead:
    "When you share your repair, you help someone else choose to fix it instead of throwing it away. That's how Fix Finder grows — and how more things stay in use.",
  downloadPostImage: "Download image as JPG",
  shareStory: "Story",
  sharePost: "Post",
  shareFbStory: "Facebook Story",
  shareFbPost: "Facebook Post",
  shareIgStory: "Instagram Story",
  shareIgPost: "Instagram Post",
  shareSizeStory: "9:16 · 1080 × 1920",
  shareSizePost: "4:5 · 1080 × 1350",
  sharePreparing: "Preparing image…",
  shareShared: "Ready to post",
  shareOpened:
    "Opened with your photo. If the picture is missing, add the saved image from Downloads.",
  sharePopupBlocked:
    "Your photo was saved. Allow pop-ups, then tap again to open Facebook or Instagram.",
  shareHintDownload: "Image saved.",
  shareHintStory: "Story image saved. Add it to your story from your camera roll.",
  shareHintPost: "Post image saved. Add it to a new post from your camera roll.",
  publishing: "Sharing…",
  storageFull:
    "Those photos are too large to save on this device. Please try smaller photos.",
  dataTitle: "How we handle your data",
  dataNote:
    "No login. Your photo is analyzed by Google Gemini and is not saved on our servers — we log text only (item, material, damage, and the product recommended). Community photos are published only when you choose to share them, after automatic review.",
  dataContact: "Contact support",
  legalTrademark:
    "Repair guidance is AI-generated and provided as a guide only. Product names are examples; always follow the instructions on the pack you buy.",
};
